### PR TITLE
Use GitHub actions instead of CircleCI

### PR DESCRIPTION
**Pull request by Matt-Gleich**
Just have to add `AIRTABLE_API_KEY` to your repo secrets.

### CODE REVIEW

**Comment by maxwofford** [comment]
@Matt-Gleich any luck getting this working? I'd love to stick with GitHub Actions, but it doesn't look like the tests have been passing

**Comment by Matt-Gleich** [comment]
Hmm let me take a look

**Comment by Matt-Gleich** [comment]
This is what seems to be causing the problem:
```
Test Suites: 5 passed, 5 total
Tests:       40 passed, 40 total
Snapshots:   0 total
Time:        10.263s
Ran all test suites.

Jest has detected the following 1 open handle potentially keeping Jest from exiting:

  ●  TCPSERVERWRAP

      30 | app.use('/v0.1', routerV0_1)
      31 | 
    > 32 | export const server = app.listen(process.env.PORT || 0, () =>
         |                           ^
      33 |   console.log(`Up and listening on ${server.address().port}`)
      34 | )
      35 | 

      at Function.listen (node_modules/express/lib/application.js:618:24)
      at Object.<anonymous> (src/index.js:32:27)
```

**Comment by maxwofford** [comment]
@Matt-Gleich Can you fix this?

**Comment by Matt-Gleich** [comment]
I am not experienced enough to fix this. Would @lachlanjc be able to?

**Pull request merged**
