### PR TITLE
Add event info

### PR DESCRIPTION
**Pull request by maxwofford**

### CODE REVIEW

**Comment by maxwofford** [comment]
Yeah, sorry for delay here. Was waiting for an airtable base w/ up-to-date events list

**Comment by maxwofford** [comment]
screw it, i'll open up what we have atm.

**Comment by maxwofford** [comment]
@lachlanjc: https://api2.hackclub.com/v0/hackathons.hackclub.com/applications?select={"filterByFormula":"approved=1"}

**Comment by maxwofford** [comment]
@thesephist heads up i added this table to the whitelist. applicant email isn't on the whitelist

**Comment by lachlanjc** [comment]
Thanks so much! Linus migrated the data so we should be good, though I haven't confirmed if 100% of it is there yet

**Comment by thesephist** [comment]
A lot of the old data isn't there. All new events should be in both places. I have no idea of a good efficient way to migrate old event data that is only in API database and not Google sheets or something

**Comment by lachlanjc** [comment]
If you open rails console you can probably just query events & do .to_json or generate a CSV & copy-paste :) super hacky for sure but

**Pull request merged**
