### PR TITLE
Initial creation of versioning system, add v0.1

### PR DESCRIPTION
**Pull request by maxwofford**

### CODE REVIEW

**Comment by maxwofford** [comment]
Thanks for the feedback @MatthewStanciu! Can I get your eyes on the [new readme](https://github.com/hackclub/api2/tree/initial-v0.1)?

**Comment by maxwofford** [comment]
@lachlanjc how would you like to get all club lat+lng from api2?
```js
options = {
  fields: ['lat', 'lng'],
  filterByFormula: 'AND(lat != BLANK(), lng != BLANK())'
}
endpoint = 'api2.hackclub.com/v0.1/Operations/Clubs?select=' + JSON.stringify(options)
```
or this?
```js
endpoint = `api2.hackclub.com/v0.1/Operations/Clubs/fields=['lat', 'lng']/filterByFormula='AND(lat != BLANK(), lng != BLANK())'`
```

**Comment by lachlanjc** [comment]
Hmm, don't have strong preferences about either. I guess the first makes more sense now that I see it written out that way

**Comment by maxwofford** [comment]
Merging so I can play around & iterate in production

**Comment by MatthewStanciu** [comment]
Wow, super sorry I never saw your mention @maxwofford. Happy to provide feedback on the README if you still need me to

**Comment by maxwofford** [comment]
@MatthewStanciu would love to get your thoughts on it, happy to do over slack

**Pull request merged**
